services:
  db:
    container_name: osudle-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_USER: "${MYSQL_USER}"
    ports:
      - '3306:3306'
    volumes:
      - osudle-db:/var/lib/mysql
  api:
    container_name: osudle-api
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    build: ./client
    image: nginx:latest
    container_name: nginx-web
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - api
    volumes:
      - ./data/nginx/conf/:/etc/nginx/conf.d/
      - ./data/certbot/www/:/var/www/certbot/
      - ./data/certbot/conf/:/etc/nginx/ssl/
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/www/:/var/www/certbot/
      - ./data/certbot/conf/:/etc/letsencrypt/
    depends_on:
      - nginx
volumes:
  osudle-db:
